sudo: false
dist: trusty

language: php

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
    global:
        - BUILD_CACHE_DIR=$HOME/.build-cache
        - TRAVIS_BUILD_DIR=.travis/build

services:
  - mysql
  - memcached

php:
  - '7.1'

before_install:
  - .travis/before_install.sh

install:
  - .travis/install.sh

before_script:
  - .travis/before_script.sh

script:
  - .travis/script.sh

after_failure:
  - .travis/after_failure.sh

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - $BUILD_CACHE_DIR
