imports: ["behat.yml.dist"]

default:
    extensions:
        Behat\MinkExtension:
            base_url: 'https://127.0.0.1:8000'

        Lakion\Behat\MinkDebugExtension:
            directory: .travis/build
            clean_start: false
            screenshot: true

        FriendsOfBehat\SymfonyExtension:
            kernel:
                environment: test
                debug: false
